### ISSUE TITLE
no 'Lincoln Sea' iho area in results

### ISSUE THREAD

**Issue by LennertSchepers** [iobis/woa#1]
Hi Pieter
I noticed that there is no 'Lincoln Sea' in the results. (http://marineregions.org/gazetteer.php?p=details&id=4254)
Is that because there are no invertebrate observations? (or because you don't have these area - which would surprise me)

Thanks
Lennert S

**Comment by pieterprovoost** [comment]
@LennertSchepers It seems that we have only one (vertebrate) record for that area: 

- https://mapper.obis.org/?areaid=34254
- https://api.obis.org/occurrence?areaid=34254

**Comment by LennertSchepers** [comment]
Ah, clearly not an invertebrate :) Thanks!
