### ISSUE TITLE
bathymetry data source

### ISSUE THREAD

**Issue by LennertSchepers** [iobis/woa#2]
Hi Pieter, could you mention the source of the bathymetry data?
Is it GEBCO_2014 or GEBCO_2019? (https://www.gebco.net/data_and_products/gridded_bathymetry_data/)
Thanks

**Comment by pieterprovoost** [comment]
@LennertSchepers See https://github.com/iobis/xylookup:

- The GEBCO_2014 Grid, version 20150318, http://www.gebco.net.
- EMODnet Bathymetry Consortium (2016): EMODnet Digital Bathymetry (DTM). http://doi.org/10.12770/c7b53704-999d-4721-b1a3-04ec60c87238.

**Comment by LennertSchepers** [comment]
So it takes the EMODnet Bathymetry (smaller resolution), and where no EMODnet data, it takes GEBCO?

**Comment by pieterprovoost** [comment]
Yes, correct.
